contact_links:
  - name: Twilio Support
    url: https://twilio.com/help/contact
    about: Get Support
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/terraform-provider-twilio+or+twilio+terraform
    about: Ask questions on Stack Overflow
  - name: Documentation
    url: https://www.twilio.com/docs/libraries/reference/terraform-provider-twilio
    about: View Reference Documentation
